### ISSUE TITLE
'No method name 'decodeSpURL_preProc' in class Tutorboy\Blogmaster\Hooks\Real    UrlHooks' 

### ISSUE THREAD

**Issue by papckoff** [midhundevasia/typo3-blogmaster#1]
Hi!

PHP 5.6.24, TYPO3 7.6.13, RealUrl 2.1.5,  Blogmaster 1.0.5.
After the installation displays an error 'No method name 'decodeSpURL_preProc' in class Tutorboy\Blogmaster\Hooks\Real   UrlHooks' (84 chars) 

In Backend: 
Database analyzer

Change fields
 select/deselect all
 ALTER TABLE tx_blogmaster_domain_model_blog CHANGE uid uid bigint(20) unsigned NOT NULL AUTO_INCREMENT; 
Current value: bigint(20) unsigned NOT NULL auto_increment
 ALTER TABLE tx_blogmaster_domain_model_post CHANGE uid uid bigint(20) unsigned NOT NULL AUTO_INCREMENT; 
Current value: bigint(20) unsigned NOT NULL auto_increment
 ALTER TABLE tx_blogmaster_domain_model_post CHANGE title title text COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: text NOT NULL
ALTER TABLE tx_blogmaster_domain_model_post CHANGE content content longtext COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: longtext NOT NULL
ALTER TABLE tx_blogmaster_domain_model_post CHANGE slug slug varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(200) NOT NULL default ''
 ALTER TABLE tx_blogmaster_domain_model_post CHANGE excerpt excerpt text COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: text NOT NULL
ALTER TABLE tx_blogmaster_domain_model_post CHANGE status status varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL default 'publish'; 
Current value: varchar(20) NOT NULL default 'publish'
ALTER TABLE tx_blogmaster_domain_model_post CHANGE comment_status comment_status varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL default 'open'; 
Current value: varchar(20) NOT NULL default 'open'
 ALTER TABLE tx_blogmaster_domain_model_category CHANGE uid uid bigint(20) unsigned NOT NULL AUTO_INCREMENT; 
Current value: bigint(20) unsigned NOT NULL auto_increment
ALTER TABLE tx_blogmaster_domain_model_category CHANGE title title varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: varchar(200) NOT NULL default NULL
ALTER TABLE tx_blogmaster_domain_model_category CHANGE description description longtext COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: longtext NOT NULL
ALTER TABLE tx_blogmaster_domain_model_category CHANGE slug slug varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(200) NOT NULL default ''
 ALTER TABLE tx_blogmaster_domain_model_tag CHANGE uid uid bigint(20) unsigned NOT NULL AUTO_INCREMENT; 
Current value: bigint(20) unsigned NOT NULL auto_increment
ALTER TABLE tx_blogmaster_domain_model_tag CHANGE title title varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: varchar(200) NOT NULL default NULL
ALTER TABLE tx_blogmaster_domain_model_tag CHANGE description description longtext COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: longtext NOT NULL
ALTER TABLE tx_blogmaster_domain_model_tag CHANGE slug slug varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(200) NOT NULL default ''
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE uid uid bigint(20) unsigned NOT NULL AUTO_INCREMENT; 
Current value: bigint(20) unsigned NOT NULL auto_increment
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE author_name author_name tinytext COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: tinytext NOT NULL
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE author_email author_email varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(100) NOT NULL default ''
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE author_url author_url varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(200) NOT NULL default ''
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE author_Ip author_Ip varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(100) NOT NULL default ''
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE content content text COLLATE utf8mb4_unicode_ci NOT NULL; 
Current value: text NOT NULL
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE status status varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL default 'pending'; 
Current value: varchar(20) NOT NULL default 'pending'
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE agent agent varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL default ''; 
Current value: varchar(255) NOT NULL default ''
ALTER TABLE tx_blogmaster_domain_model_comment CHANGE type type varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL default 'comment'; 
Current value: varchar(20) NOT NULL default 'comment'

**Comment by midhundevasia** [comment]
Hi @papckoff 
Thank you for the comment. I will fix those bugs in the next release 1.0.6, you can expect the new release within two days.

**Comment by papckoff** [comment]
Thank you
