### ISSUE TITLE
Where to edit the date

### ISSUE THREAD

**Issue by HorstBaumann** [midhundevasia/typo3-blogmaster#3]
new posts have the date of their creation,
but is there a chance to edit the datetime manually ?
(it's very essential - is this function really missing? - maybe I'm just overlooking it...?) 

Thanks 
Frank

**Comment by midhundevasia** [comment]
Hi Frank,

Yes, post date and schedule is essential, I worked on that and added in `1.0.6`.
<img width="324" alt="screen shot 2016-12-04 at 3 24 13 am" src="https://cloud.githubusercontent.com/assets/197399/20862460/430cadbc-b9d1-11e6-93e3-dd20442d1c48.png">


Regards,
Midhun Devasia
